# target hostname or group name

- hosts: target_servers
# define tasks

  tasks:
# task name (any name you like)

  - name: Test Task
# use file module to set the file state

    file: path=/tmp/test.conf state=touch owner=cent group=cent mode=0600 
