---
- name: Multi-containers
  hosts: all
  become: true
  vars:
      firewall_pkg: firewalld
      web_pkg: httpd
      web_svc: httpd
      ssl_pkg: mod_ssl
      python_pkg: python-passlib
      httpdconf_src: files/httpd.conf
      httpdconf_file: /etc/httpd/conf/httpd.conf
      web_root: /var/www/html
      web_user: guest
  tasks:
    - name: Latest version of necessary packages installed
      yum:
        name:
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest

    - name: Configure web service
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_file }}"
        owner: root
        group: root
        mode: 0644
    
    - name: Create index.html
      copy:
        content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4'] ['address'] }}) has been customized by Ansible.\n"
        dest: "{{ web_root }}/index.html"

    - name: Open the port for the web server
      firewalld:
        service: https
        state: enabled
        immediate: true
        permanent: true

    - name: Web service enabled and restarted
      service:
        name: "{{ web_svc }}"
        state: restarted
        enabled: true

    - name: Firewall service enable and restarted
      service:
        name: firewalld
        state: restarted
        enabled: true



