---
- name: Setup Message of the Day ....
  hosts: all
  become: true
  tasks:
    - name: Copy /etc/motd
      copy:
        dest: /etc/motd
        content: |
           This system is managed by Ansible
           The system name is {{ ansible_hostname }} The IP address is {{ ansible_default_ipv4.address }}
