# target hostname or group name

- hosts: all
# define tasks

  tasks:
# task name (any name you like)

  - name: Test Task
# use file module to set the file state

    file: path=/home/mahsan/test.conf state=touch owner=mahsan group=mahsan mode=0600
